USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/innos/AD682J/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7x27a
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

#TARGET_BOOTLOADER_BOARD_NAME := AD682J

BOARD_KERNEL_CMDLINE := androidboot.hardware=qcom loglevel=1 vmalloc=400M
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 13901824
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 13901824
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 681574400
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2923429888
BOARD_USERCACHEIMAGE_PARTITION_SIZE := 104857600
BOARD_FLASH_BLOCK_SIZE := 131072
MIUI_DEVICE_CONF := ../../../device/innos/AD682J/device.conf
MIUI_INIT_CONF := ../../../device/innos/AD682J/init.conf
TARGET_PREBUILT_KERNEL := device/innos/AD682J/kernel
TARGET_RECOVERY_INITRC := device/innos/AD682J/init.rc
TARGET_RECOVERY_FSTAB := device/innos/AD682J/overlay/recovery.fstab
#BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/innos/AD682J/recovery/recovery_keys.c
BOARD_CUSTOM_GRAPHICS := ../../../device/innos/AD682J/recovery/graphics.c
BOARD_UMS_LUNFILE := "/sys/devices/platform/msm_hsusb/gadget/lun"
BOARD_REC_LANG_ENGLISH := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/msm_hsusb/gadget/lun%d/file"
TARGET_USERIMAGES_USE_EXT4 := true

BOARD_NO_TOUCHSCREEN := false
BOARD_HAS_NO_SELECT_BUTTON := true
#TWRP
DEVICE_RESOLUTION := 540x960
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_FLASH_FROM_STORAGE := true	  	
TW_HAS_DOWNLOAD_MODE := true
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true
TW_MAX_BRIGHTNESS := 255
TW_BRIGHTNESS_PATH := "/sys/class/leds/lcd-backlight/brightness"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_HAS_NO_REAL_SDCARD := true
TW_INCLUDE_DUMLOCK := true
RECOVERY_TOUCHSCREEN_SWAP_XY := true
RECOVERY_TOUCHSCREEN_FLIP_Y := true
RECOVERY_TOUCHSCREEN_FLIP_X := true
TW_ALWAYS_RMRF := true
TW_INCLUDE_INJECTTWRP := true
TW_DEFAULT_EXTERNAL_STORAGE := true
HAVE_SELINUX := true 
TWRP_EVENT_LOGGING := true
BOARD_HAS_FLIPPED_SCREEN := true 
TARGET_PREBUILT_RECOVERY_KERNEL := device/innos/AD682J/kernel
# End TWRP
